# global configuration
global:
  scrape_interval: 15s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
{{ range .Targets }}
  - job_name: {{ .Address }}
    scheme: {{ .Scheme }}
    static_configs:
      - targets:
          - {{ .Address }}
{{ end }}
